[/Script/Engine.RendererSettings]
; Linux uses the Vulkan SM5 fallback rendering path.
r.DynamicGlobalIlluminationMethod=0
r.ReflectionMethod=2
r.RayTracing=False
r.RayTracing.RayTracingProxies.ProjectEnabled=False
r.Lumen.Supported=0
r.Nanite.ProjectEnabled=False
r.Shadow.Virtual.Enable=0
r.Shadow.Virtual.ProjectEnabled=0
